apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: configmap
    app.kubernetes.io/part-of: {{ template "fullname" . }}
data:
  application.properties: |-
    api.token= ${API_TOKEN}

kind: ConfigMap
