apiVersion: v1
kind: Secret
metadata:
  name: application-secret
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: {{ template "fullname" . }}
type: Opaque
stringData:
  sampleApiToken: 123456SuperSecretData
